### ISSUE TITLE
ctrl+v pastes copied text twice

### ISSUE THREAD

**Issue by ketax** [textadventures/squiffy-editor#8]
Pasting text into editor using keyboard shortcut pastes copied text twice. Pasting using corresponding menu item works as intended. 

tested on: Squiffy editor 4.0.0 linux version on linux mint.

**Comment by alexwarren** [comment]
I have had a look at this but I can't figure out why it's happening. I've tried a few workarounds - disable the Ace editor's own paste command, skipping Squiffy's own paste code, but they either don't work (still get duplicates) or they prevent pasting entirely. Sometimes the text even gets copied three times! It's really inconsistent and bizarre behaviour.

I don't know if the root of the problem lies in the Ace editor, in Electron, or somewhere between the two. I can reproduce the problem on Ubuntu. The web version works fine, as do the Mac and Windows builds.
